/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL;

/**
 *
 * @author gdemg
 */
public class tabla extends javax.swing.JFrame {

    private int id = 0;
    private int dato = 0;
    /**
     * Creates new form tablaDatos
     */
    public tabla() {
        initComponents();
        Consultas datos = new Consultas();
        datos.obtenerPropiedadesParaCambiarPrecio();
        datos.mostrarTabla(tablamuestra, Paneltabla);
        eliminarvivienda.setEnabled(false);
        disponibilidad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paneltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamuestra = new javax.swing.JTable();
        eliminarvivienda = new javax.swing.JButton();
        disponibilidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Paneltabla.setBackground(new java.awt.Color(255, 255, 255));
        Paneltabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        tablamuestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tablamuestra.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tablamuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablamuestra.setToolTipText("");
        tablamuestra.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablamuestra.setGridColor(new java.awt.Color(255, 0, 0));
        tablamuestra.setSelectionBackground(new java.awt.Color(224, 86, 91));
        tablamuestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablamuestraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablamuestra);

        javax.swing.GroupLayout PaneltablaLayout = new javax.swing.GroupLayout(Paneltabla);
        Paneltabla.setLayout(PaneltablaLayout);
        PaneltablaLayout.setHorizontalGroup(
            PaneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneltablaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PaneltablaLayout.setVerticalGroup(
            PaneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneltablaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        eliminarvivienda.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        eliminarvivienda.setText("Eliminar ");
        eliminarvivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarviviendaActionPerformed(evt);
            }
        });

        disponibilidad.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        disponibilidad.setText("Disponibilidad");
        disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Paneltabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(eliminarvivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Paneltabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarvivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarviviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarviviendaActionPerformed
        // TODO add your handling code here:
        Consultas datos = new Consultas();
        datos.eliminarDato(id);
        datos.mostrarTabla(tablamuestra, Paneltabla);
    }//GEN-LAST:event_eliminarviviendaActionPerformed

    private void tablamuestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamuestraMouseClicked
        // TODO add your handling code here:
        Consultas datos = new Consultas();
        id = Integer.parseInt(datos.selecDato(tablamuestra));
        dato = datos.selec(tablamuestra);
        eliminarvivienda.setEnabled(true);
        disponibilidad.setEnabled(true);
    }//GEN-LAST:event_tablamuestraMouseClicked

    private void disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Modifica m = new Modifica(id, dato);
        m.setVisible(true);
    }//GEN-LAST:event_disponibilidadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paneltabla;
    private javax.swing.JButton disponibilidad;
    private javax.swing.JButton eliminarvivienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablamuestra;
    // End of variables declaration//GEN-END:variables
}
